name: vt up ci

on:
  workflow_call:
    inputs:
      member:
        type: string
        required: true

jobs:
  post-random-video:
    runs-on: ubuntu-latest

    steps:
      - name: Post PR comment with random video
        uses: actions/github-script@v7
        with:
          script: |
            const endpoint = "https://vt.imgs.shiron.dev/${{ inputs.member }}";

            const response = await fetch(`${endpoint}/thumbnails.json`);
            const data = await response.json();

            const videos = data.videos;
            const randomIndex = Math.floor(Math.random() * videos.length);
            const selectedVideo = videos[randomIndex];

            const imageUrl = `${endpoint}/${selectedVideo.thumbnail}`;
            const videoUrl = selectedVideo.url;
            const title = selectedVideo.title;
            const description = selectedVideo.description;

            const body = `\
            Here is a random video for you! 🎥

            ## ${title}
            > ${description}

            [![Thumbnail](${imageUrl})](${videoUrl})\
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
